apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: {{ .Values.service.type}}
  selector:
    purpose: templatise the manifest files
    project: roboshop
  ports:
  - protocol: TCP
    port: {{ .Values.service.servicePort}}
    targetPort: 8080